### ISSUE TITLE
upload error - IndexError: tuple index out of range 

### ISSUE THREAD

**Issue by doomsayr** [Backblaze/B2_Command_Line_Tool#380]
Command used -
b2 upload-file bucketName File.name File.name

50% through the first time of a 1GB file, then 80% the second time this same error occurred.
Version 0.7.2 of the tool.

Traceback (most recent call last):
 File "/usr/local/bin/b2", line 11, in <module>
   load_entry_point('b2==0.7.2', 'console_scripts', 'b2')()
 File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 1104, in main
   exit_status = ct.run_command(decoded_argv)
 File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 992, in run_command
   return command.run(args)
 File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 919, in run
   progress_listener=progress_listener
 File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
   return function(*wrapee_args, **wrapee_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 321, in upload_local_file
   progress_listener=progress_listener
 File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
   return function(*wrapee_args, **wrapee_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 372, in upload
   upload_source, file_name, content_type, file_info, progress_listener
 File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 450, in _upload_large_file
   part_sha1_array = [interruptible_get_result(f)['contentSha1'] for f in part_futures]
 File "/usr/local/lib/python2.7/dist-packages/b2/utils.py", line 60, in interruptible_get_result
   return future.result(timeout=1.0)
 File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 422, in result
   return self.__get_result()
 File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 62, in run
   result = self.fn(*self.args, **self.kwargs)
 File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 539, in _upload_part
   input_stream
 File "/usr/local/lib/python2.7/dist-packages/b2/raw_api.py", line 467, in upload_part
   return self.b2_http.post_content_return_json(upload_url, headers, data_stream)
 File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 259, in post_content_return_json
   response = _translate_and_retry(do_post, try_count, post_params)
 File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 103, in _translate_and_retry
   return _translate_errors(fcn, post_params)
 File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 71, in _translate_errors
   if e2.args[1] == 'Broken pipe':
IndexError: tuple index out of range

**Comment by doomsayr** [comment]
Another error but from the sync command and on version 0.7.2: 
ERROR:b2.sync.action:an exception occurred in a sync action9 MB/s 
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/b2/sync/action.py", line 42, in run 
self.do_action(bucket, reporter) 
File "/usr/local/lib/python2.7/dist-packages/b2/sync/action.py", line 84, in do_action 
progress_listener=SyncFileReporter(reporter) 
File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper 
return function(*wrapee_args, **wrapee_kwargs) 
File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 372, in upload 
upload_source, file_name, content_type, file_info, progress_listener 
File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 450, in _upload_large_file 
part_sha1_array = [interruptible_get_result(f)['contentSha1'] for f in part_futures] 
File "/usr/local/lib/python2.7/dist-packages/b2/utils.py", line 60, in interruptible_get_result 
return future.result(timeout=1.0) 
File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 422, in result 
return self.__get_result() 
File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 62, in run 
result = self.fn(*self.args, **self.kwargs) 
File "/usr/local/lib/python2.7/dist-packages/b2/bucket.py", line 539, in _upload_part 
input_stream 
File "/usr/local/lib/python2.7/dist-packages/b2/raw_api.py", line 467, in upload_part 
return self.b2_http.post_content_return_json(upload_url, headers, data_stream) 
File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 259, in post_content_return_json 
response = _translate_and_retry(do_post, try_count, post_params) 
File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 103, in _translate_and_retry 
return _translate_errors(fcn, post_params) 
File "/usr/local/lib/python2.7/dist-packages/b2/b2http.py", line 71, in _translate_errors 
if e2.args[1] == 'Broken pipe': 
IndexError: tuple index out of range 
b2_upload(/mnt/storage/b2/base.tar, base.tar, 1508763390837): IndexError('tuple index out of range',) tuple index out of range 
ERROR:b2.console_tool:ConsoleTool command error 
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 992, in run_command 
return command.run(args) 
File "/usr/local/lib/python2.7/dist-packages/b2/console_tool.py", line 781, in run 
dry_run=args.dryRun, 
File "/usr/local/lib/python2.7/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper 
return function(*wrapee_args, **wrapee_kwargs) 
File "/usr/local/lib/python2.7/dist-packages/b2/sync/sync.py", line 263, in sync_folders 
raise CommandError('sync is incomplete') 
CommandError: sync is incomplete 
ERROR: sync is incomplete

**Comment by svonohr** [comment]
The 'tuple index out of range' error was fixed in PR #356 (not yet released). Anyway, this seems like a connection issue. Is your internet connection stable and have you tried uploading using fewer threads? It defaults to 10 threads which can be reduced using the `--threads` option. Try using two or even a single thread and see if the problem persists.

**Comment by dougwyu** [comment]
i have the same error.  When will the fix be released? 

Traceback (most recent call last):
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 304, in _send_until_done
    return self.connection.send(data)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1256, in send
    self._raise_ssl_error(self._ssl, result)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1166, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 905, in send
    self.sock.sendall(datablock)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 316, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 311, in _send_until_done
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/http/client.py", line 905, in send
    self.sock.sendall(datablock)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 316, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 311, in _send_until_done
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/b2http.py", line 47, in _translate_errors
    response = fcn()
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/b2http.py", line 255, in do_post
    response = self.session.post(url, headers=headers, data=data)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home/b042/.local/bin/b2", line 11, in <module>
    sys.exit(main())
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/console_tool.py", line 1104, in main
    exit_status = ct.run_command(decoded_argv)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/console_tool.py", line 992, in run_command
    return command.run(args)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/console_tool.py", line 919, in run
    progress_listener=progress_listener
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/bucket.py", line 321, in upload_local_file
    progress_listener=progress_listener
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/bucket.py", line 372, in upload
    upload_source, file_name, content_type, file_info, progress_listener
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/bucket.py", line 450, in _upload_large_file
    part_sha1_array = [interruptible_get_result(f)['contentSha1'] for f in part_futures]
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/bucket.py", line 450, in <listcomp>
    part_sha1_array = [interruptible_get_result(f)['contentSha1'] for f in part_futures]
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/utils.py", line 60, in interruptible_get_result
    return future.result(timeout=1.0)
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/gpfs/software/python/anaconda/4.2/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/bucket.py", line 539, in _upload_part
    input_stream
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/raw_api.py", line 467, in upload_part
    return self.b2_http.post_content_return_json(upload_url, headers, data_stream)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/b2http.py", line 259, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/b2http.py", line 103, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/gpfs/home/b042/.local/lib/python3.5/site-packages/b2/b2http.py", line 71, in _translate_errors
    if e2.args[1] == 'Broken pipe':
IndexError: tuple index out of range

**Comment by ppolewicz** [comment]
@bwbeach could we release a version with my fix? It seems like a common issue (that's why I fixed it).
On the other hand, I think we have a backwards-incompatible change in sync, which should be released at a separate branch & major version.

**Comment by bwbeach** [comment]
I'm planning on releasing a new major version this week.  There are several good changes since the last release.

Do you think it's important to release a compatible version with the fix before going to the next major version?

**Comment by ppolewicz** [comment]
I think old versions should still have some support until they hit EOL (which should not be the same day as release of the new version). This fix that I've done is a type of thing that hits production systems sometimes, people may want to have an ability to upgrade to something and get improved retry mechanism (not stopping everything on one broken socket) without getting the new `sync` syntax which forces them into audit and maybe development.
